-- Since 'foo' does not exist, call foo() is logic error 
foo()